Skills = {
    {"Target_PetrifyingTouch", {""}, "None"},
    {"Shout_FleshSacrifice", {""}, "None"},
    {"Cone_Flamebreath", {""}, "None"},
    {"Shout_InspireStart", {""}, "None"},
    {"Shout_PlayDead", {""}, "None"},

    {"Summon_SoulWolf", {""}, "None"},
    {"Target_MaddeningSong", {""}, "None"},
    {"Target_DemonicStare", {""}, "None"},
    {"Shout_BreakTheShackles", {""}, "None"},
    {"Target_Squall", {""}, "None"},
    {"Target_TimeWarp", {""}, "None"},
    {"Dome_CircleOfProtection", {""}, "None"},

    {"Shout_Adrenaline", {"RogueLore"}, "None"},
    {"Projectile_ThrowingKnife", {"RogueLore"}, "Dagger"},
    {"Projectile_Chloroform", {"RogueLore"}, "None"},
    {"MultiStrike_Vault", {"RogueLore"}, "Dagger"},
    {"Target_Restoration", {"WaterSpecialist"}, "None"},
    {"ProjectileStrike_HailStrike", {"WaterSpecialist"}, "None"},
    {"Rain_Water", {"WaterSpecialist"}, "None"},
    {"Target_FrostyShell", {"WaterSpecialist"}, "None"},
    {"Projectile_PinDown", {"RangerLore"}, "Bow"},
    {"Projectile_Ricochet", {"RangerLore"}, "Bow"},
    {"Target_FirstAid", {"RangerLore"}, "None"},
    {"Target_ElementalArrowheads", {"RangerLore"}, "Bow"},
    {"Cone_GroundSmash", {"WarriorLore"}, "Dagger"},
    {"Projectile_BouncingShield", {"WarriorLore"}, "Dagger"},
    {"Rush_BatteringRam", {"WarriorLore"}, "Dagger"},
    {"Target_CripplingBlow", {"WarriorLore"}, "Dagger"},
    {"Projectile_DimensionalBolt", {"Summoning"}, "None"},
    {"Summon_TotemFromSurface", {"Summoning"}, "None"},
    {"Summon_Incarnate", {"Summoning"}, "Incarnate"},
    {"Target_RangedInfusion", {"Summoning"}, "IncarnateBuff"},
    {"Projectile_FlamingDaggers", {"FireSpecialist"}, "None"},
    {"Shout_Ignition", {"FireSpecialist"}, "None"},
    {"Target_BurnMyEyes", {"FireSpecialist"}, "None"},
    {"Target_Haste", {"FireSpecialist"}, "None"},
    {"Projectile_PyroclasticRock", {"EarthSpecialist"}, "None"},
    {"Projectile_PoisonDartStart", {"EarthSpecialist"}, "None"},
    {"Shout_Contamination", {"EarthSpecialist"}, "None"},
    {"Target_Fortify", {"EarthSpecialist"}, "None"},
    {"Shout_FavourableWind", {"AirSpecialist"}, "None"},
    {"Shout_BlindingRadiance", {"AirSpecialist"}, "None"},
    {"Projectile_LightningBolt", {"AirSpecialist"}, "None"},
    {"Target_ShockingTouch", {"AirSpecialist"}, "None"},
    {"Shout_ChameleonSkin", {"Polymorph"}, "None"},
    {"Shout_BullHorns", {"Polymorph"}, "None"},
    {"Target_TentacleLash", {"Polymorph"}, "None"},
    {"Target_ChickenTouch", {"Polymorph"}, "None"},
    {"Target_DecayingTouch", {"Necromancy"}, "None"},
    {"Target_MosquitoSwarm", {"Necromancy"}, "None"},
    {"Target_BloodBubble", {"Necromancy"}, "None"},
    {"Target_BloatedCorpse", {"Necromancy"}, "None"},

    {"Projectile_ChainHeal", {"WaterSpecialist", "WaterSpecialist"}, "None"},
    {"Projectile_IceFan", {"WaterSpecialist", "WaterSpecialist"}, "None"},
    {"Shout_GlobalCooling", {"WaterSpecialist", "WaterSpecialist"}, "None"},
    {"Shout_FrostAura", {"WaterSpecialist", "WaterSpecialist"}, "None"},
    {"Target_WinterBlast", {"WaterSpecialist", "WaterSpecialist"}, "None"},
    {"Target_CryogenicStasis", {"WaterSpecialist", "WaterSpecialist"}, "None"},
    {"Shout_IceBreaker", {"WaterSpecialist", "WaterSpecialist", "WaterSpecialist"}, "None"},
    {"Cone_Shatter", {"WaterSpecialist", "WaterSpecialist", "WaterSpecialist"}, "None"},
    {"Target_CleanseWounds", {"WaterSpecialist", "WarriorLore"}, "None"},
    {"Target_VampiricHunger", {"WaterSpecialist", "RogueLore"}, "None"},
    {"Target_WaterInfusion", {"WaterSpecialist", "Summoning"}, "IncarnateBuff"},
    {"Rain_Blood", {"WaterSpecialist", "Necromancy"}, "None"},
    {"Shout_Cryotherapy", {"WaterSpecialist", "RangerLore"}, "None"},
    {"Shout_HealingTears", {"WaterSpecialist", "Polymorph"}, "None"},
    {"Quake_Earthquake", {"EarthSpecialist", "EarthSpecialist"}, "None"},
    {"Shout_MendMetal", {"EarthSpecialist", "EarthSpecialist"}, "None"},
    {"Shout_PoisonWave", {"EarthSpecialist", "EarthSpecialist"}, "None"},
    {"Shout_ReactiveArmor", {"EarthSpecialist", "EarthSpecialist"}, "None"},
    {"Target_RockSpikes", {"EarthSpecialist", "EarthSpecialist"}, "None"},
    {"Target_WormTremor", {"EarthSpecialist", "EarthSpecialist"}, "None"},
    {"Shout_SiphonPoison", {"EarthSpecialist", "EarthSpecialist", "EarthSpecialist"}, "None"},
    {"Wall_LivingWall", {"EarthSpecialist", "EarthSpecialist", "EarthSpecialist"}, "None"},
    {"Target_PoisonInfusion", {"EarthSpecialist", "Summoning"}, "IncarnateBuff"},
    {"Target_CorrosiveTouch", {"EarthSpecialist", "Necromancy"}, "None"},
    {"Target_Condense", {"EarthSpecialist", "Polymorph"}, "None"},
    {"Projectile_ThrowDust", {"EarthSpecialist", "RangerLore"}, "None"},
    {"Shout_OilyCarapace", {"EarthSpecialist", "WarriorLore"}, "None"},
    {"Shout_VenomCoating", {"EarthSpecialist", "RogueLore"}, "None"},
    {"Projectile_Fireball", {"FireSpecialist", "FireSpecialist"}, "None"},
    {"Shout_Supernova", {"FireSpecialist", "FireSpecialist"}, "None"},
    {"Shout_FlamingTongues", {"FireSpecialist", "FireSpecialist"}, "None"},
    {"Target_FireWhip", {"FireSpecialist", "FireSpecialist"}, "None"},
    {"Target_SpontaneousCombustion", {"FireSpecialist", "FireSpecialist"}, "None"},
    {"Zone_LaserRay", {"FireSpecialist", "FireSpecialist"}, "None"},
    {"Shout_FireBrand", {"FireSpecialist", "FireSpecialist", "FireSpecialist"}, "None"},
    {"Target_FlamingCrescendo", {"FireSpecialist", "FireSpecialist", "FireSpecialist"}, "None"},
    {"Target_Sabotage", {"FireSpecialist", "RogueLore"}, "None"},
    {"Target_FireInfusion", {"FireSpecialist", "Summoning"}, "IncarnateBuff"},
    {"Target_Fireblood", {"FireSpecialist", "Polymorph"}, "None"},
    {"Target_CorpseExplosion", {"FireSpecialist", "Necromancy"}, "None"},
    {"Shout_SparkingSwings", {"FireSpecialist", "WarriorLore"}, "Dagger"},
    {"Projectile_LaunchExplosiveTrap", {"FireSpecialist", "RangerLore"}, "None"},
    {"ProjectileStrike_DazingBolt", {"AirSpecialist", "AirSpecialist"}, "None"},
    {"Target_PressureSpike", {"AirSpecialist", "AirSpecialist"}, "None"},
    {"Target_Apportation", {"AirSpecialist", "AirSpecialist"}, "None"},
    {"Target_EvasiveManeuver", {"AirSpecialist", "AirSpecialist"}, "None"},
    {"Teleportation_Netherswap", {"AirSpecialist", "AirSpecialist"}, "None"},
    {"Teleportation_FreeFall", {"AirSpecialist", "AirSpecialist"}, "None"},
    {"Projectile_Superconductor", {"AirSpecialist", "AirSpecialist", "AirSpecialist"}, "None"},
    {"Tornado_Air", {"AirSpecialist", "AirSpecialist", "AirSpecialist"}, "None"},
    {"Target_ElectricInfusion", {"AirSpecialist", "Summoning"}, "IncarnateBuff"},
    {"Target_Windwalker", {"AirSpecialist", "RangerLore"}, "None"},
    {"Target_Vaporize", {"AirSpecialist", "Polymorph"}, "None"},
    {"Shout_BreathingBubble", {"AirSpecialist", "WarriorLore"}, "None"},
    {"Shout_SmokeCover", {"AirSpecialist", "RogueLore"}, "None"},
    {"Target_VacuumTouch", {"AirSpecialist", "Necromancy"}, "None"},
    {"Projectile_LaunchOilBlob", {"Polymorph", "Polymorph"}, "None"},
    {"Shout_Wings", {"Polymorph", "Polymorph"}, "None"},
    {"Shout_SteelSkin", {"Polymorph", "Polymorph"}, "None"},
    {"Shout_MedusaHead", {"Polymorph", "Polymorph"}, "None"},
    {"Shout_SpiderLegs", {"Polymorph", "Polymorph"}, "None"},
    {"Teleportation_SwapGround", {"Polymorph", "Polymorph"}, "None"},
    {"Target_StripResistance", {"Polymorph", "Polymorph", "Polymorph"}, "None"},
    {"Target_Equalize", {"Polymorph", "Polymorph", "Polymorph"}, "None"},
    {"Shout_BoneCage", {"Necromancy", "Necromancy"}, "None"},
    {"Summon_BonePile", {"Necromancy", "Necromancy"}, "None"},
    {"Target_DeathsDoor", {"Necromancy", "Necromancy"}, "None"},
    {"Target_DeathWish", {"Necromancy", "Necromancy"}, "None"},
    {"Target_ShacklesOfPain", {"Necromancy", "Necromancy"}, "None"},
    {"Target_Infect", {"Necromancy", "Necromancy"}, "None"},
    {"Cone_SilencingStare", {"Necromancy", "Necromancy", "Necromancy"}, "None"},
    {"Teleportation_LastRites", {"Necromancy", "Necromancy", "Necromancy"}, "None"},
    {"Jump_CloakAndDagger", {"RogueLore", "RogueLore"}, "None"},
    {"Target_KneeBreaker", {"RogueLore", "RogueLore"}, "Dagger"},
    {"Target_SleepingArms", {"RogueLore", "RogueLore"}, "Dagger"},
    {"Target_SerratedEdge", {"RogueLore", "RogueLore"}, "Dagger"},
    {"Target_CorruptedBlade", {"RogueLore", "RogueLore"}, "Dagger"},
    {"Target_GagOrder", {"RogueLore", "RogueLore"}, "Dagger"},
    {"Target_TerrifyingCruelty", {"RogueLore", "RogueLore", "RogueLore"}, "Dagger"},
    {"Projectile_LaunchBomber", {"RogueLore", "RogueLore", "RogueLore"}, "None"},
    {"Jump_TacticalRetreat", {"RangerLore", "RangerLore"}, "None"},
    {"Projectile_Multishot", {"RangerLore", "RangerLore"}, "Bow"},
    {"Projectile_SkyShot", {"RangerLore", "RangerLore"}, "Bow"},
    {"Projectile_PiercingShot", {"RangerLore", "RangerLore"}, "Bow"},
    {"Projectile_BallisticShot", {"RangerLore", "RangerLore"}, "Bow"},
    {"Target_ReactionShot", {"RangerLore", "RangerLore"}, "Bow"},
    {"Projectile_Snipe", {"RangerLore", "RangerLore", "RangerLore"}, "Bow"},
    {"Projectile_Mark", {"RangerLore", "RangerLore", "RangerLore"}, "None"},
    {"Jump_PhoenixDive", {"WarriorLore", "WarriorLore"}, "None"},
    {"MultiStrike_BlinkStrike", {"WarriorLore", "WarriorLore"}, "Dagger"},
    {"Shout_Whirlwind", {"WarriorLore", "WarriorLore"}, "Dagger"},
    {"Shout_Taunt", {"WarriorLore", "WarriorLore"}, "None"},
    {"Target_Enrage", {"WarriorLore", "WarriorLore"}, "None"},
    {"Shout_DeflectiveBarrier", {"WarriorLore", "WarriorLore"}, "Dagger"},
    {"Shout_GuardianAngel", {"WarriorLore", "WarriorLore", "WarriorLore"}, "None"},
    {"Target_Challenge", {"WarriorLore", "WarriorLore", "WarriorLore"}, "None"},
    {"Target_PowerInfusion", {"Summoning", "Summoning"}, "IncarnateBuff"},
    {"Target_ShadowInfusion", {"Summoning", "Summoning"}, "IncarnateBuff"},
    {"Target_Harmony", {"Summoning", "Summoning"}, "None"},
    {"Target_SoulMate", {"Summoning", "Summoning"}, "None"},
    {"Target_Charm", {"Summoning", "Summoning"}, "None"},
    {"Target_Supercharge", {"Summoning", "Summoning"}, "None"},
    {"Target_WarpInfusion", {"Summoning", "Summoning", "Summoning"}, "IncarnateBuff"},
    {"Target_Cannibalize", {"Summoning", "Summoning", "Summoning"}, "None"}
}

return Skills